repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        stages:
          - commit

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages:
          - commit

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: venv/bin/pytest -v
        always_run: true
        pass_filenames: false
        stages:
          - commit

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c "venv/bin/pip3 freeze >> requirements.txt; git add requirements.txt"
        language: system
        pass_filenames: false
        stages:
          - commit
